name: Approve and Move Prompts

on:
  issue_comment:
    types: [created]

jobs:
  process_prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Prompt Extraction
      run: |
        awk '/^### /,/^---$/' prompts/pending-approval.md | head -n 15

    - name: Check for Approval
      if: github.event.comment.body == '✅ Approved'
      run: |
        PROMPT_ENTRY=$(awk '/^### /,/^---$/' prompts/pending-approval.md)
        if [[ -z "$PROMPT_ENTRY" ]]; then
          echo "Error: No prompt found! Check pending-approval.md format."
          exit 1
        fi
        echo "Extracted Prompt: $PROMPT_ENTRY"

        # ✅ Extract and clean department name
        DEPARTMENT=$(echo "$PROMPT_ENTRY" | sed -n 's/^.*\*\*Department:\*\*: \(.*\)$/\1/p' | tr -d '\r' | xargs)
        echo "Extracted Department: '$DEPARTMENT'"

        # ✅ Use case statement for exact department matching
        case "$DEPARTMENT" in
          "Architectural Engineering")
            TARGET_FILE="prompts/engineering-architectural.md"
            ;;
          "Computer Engineering")
            TARGET_FILE="prompts/engineering-computer.md"
            ;;
          "Chemical and Petrochemical Engineering")
            TARGET_FILE="prompts/engineering-chemical.md"
            ;;
          "Construction and Building Engineering")
            TARGET_FILE="prompts/engineering-construction.md"
            ;;
          "Electronics and Communications Engineering")
            TARGET_FILE="prompts/engineering-electronics.md"
            ;;
          "Electrical and Control Engineering")
            TARGET_FILE="prompts/engineering-electrical.md"
            ;;
          "Industrial and Management Engineering")
            TARGET_FILE="prompts/engineering-industrial.md"
            ;;
          "Marine and Offshore Engineering")
            TARGET_FILE="prompts/engineering-marine.md"
            ;;
          "Mechanical Engineering")
            TARGET_FILE="prompts/engineering-mechanical.md"
            ;;
          "Oil and Gas Engineering")
            TARGET_FILE="prompts/engineering-oil.md"
            ;;
          *)
            TARGET_FILE="prompts/general.md"
            ;;
        esac

        echo "Moving prompt to: $TARGET_FILE"

        # ✅ Remove the department line before saving the prompt
        echo "$PROMPT_ENTRY" | sed '/\*\*Department:\*\*/d' >> "$TARGET_FILE"

        # ✅ Remove the prompt from pending-approval.md
        awk 'BEGIN{found=0} /^### /{found=1} found && /^---$/{found=0; next} !found' prompts/pending-approval.md > temp.md && mv temp.md prompts/pending-approval.md

        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add prompts/*
        git commit -m "Approved prompt moved to $TARGET_FILE"
        git push
