name: Approve and Move Prompts

on:
  issue_comment:
    types: [created]

jobs:
  process_prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Prompt Extraction
      run: |
        awk '/^### /,/^---$/' prompts/pending-approval.md | head -n 15

    - name: Check for Approval
      if: github.event.comment.body == '✅ Approved'
      run: |
        PROMPT_ENTRY=$(awk '/^### /,/^---$/' prompts/pending-approval.md)
        if [[ -z "$PROMPT_ENTRY" ]]; then
          echo "❌ ERROR: No prompt found! Check pending-approval.md format."
          exit 1
        fi
        echo "✅ Extracted Prompt: $PROMPT_ENTRY"

        # ✅ Extract and clean department name (Fix for repetition)
        DEPARTMENT=$(echo "$PROMPT_ENTRY" | grep -oP '(?<=\*\*Department:\*\* )[^*]+' | head -n 1 | tr -d '\r' | xargs)
        
        if [[ -z "$DEPARTMENT" ]]; then
            echo "❌ ERROR: Failed to extract department from the prompt! Check the format of pending-approval.md."
            exit 1
        fi

        echo "✅ DEBUG: Extracted Department: '$DEPARTMENT'"

        # ✅ Define list of valid department names
        DEPARTMENTS=("Architectural Engineering"
                     "Computer Engineering"
                     "Chemical and Petrochemical Engineering"
                     "Construction and Building Engineering"
                     "Electronics and Communications Engineering"
                     "Electrical and Control Engineering"
                     "Industrial and Management Engineering"
                     "Marine and Offshore Engineering"
                     "Mechanical Engineering"
                     "Oil and Gas Engineering")

        # ✅ Define corresponding file paths
        FILES=("prompts/engineering-architectural.md"
               "prompts/engineering-computer.md"
               "prompts/engineering-chemical.md"
               "prompts/engineering-construction.md"
               "prompts/engineering-electronics.md"
               "prompts/engineering-electrical.md"
               "prompts/engineering-industrial.md"
               "prompts/engineering-marine.md"
               "prompts/engineering-mechanical.md"
               "prompts/engineering-oil.md")

        # ✅ First, check for an exact match
        for i in "${!DEPARTMENTS[@]}"; do
            if [[ "$DEPARTMENT" == "${DEPARTMENTS[$i]}" ]]; then
                TARGET_FILE="${FILES[$i]}"
                echo "✅ DEBUG: Exact Match Found - Moving to $TARGET_FILE"
                break
            fi
        done

        # ✅ If no exact match, default to general.md
        if [[ -z "$TARGET_FILE" ]]; then
            TARGET_FILE="prompts/general.md"
        fi

        echo "✅ Final Assigned Department: '$DEPARTMENT'"
        echo "✅ Moving prompt to: $TARGET_FILE"

        # ✅ Remove the department line before saving the prompt
        echo "$PROMPT_ENTRY" | sed '/\*\*Department:\*\*/d' >> "$TARGET_FILE"

        # ✅ Remove the prompt from pending-approval.md
        awk 'BEGIN{found=0} /^### /{found=1} found && /^---$/{found=0; next} !found' prompts/pending-approval.md > temp.md && mv temp.md prompts/pending-approval.md

        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add prompts/*
        git commit -m "Approved prompt moved to $TARGET_FILE"
        git push
