name: Approve and Move Prompts

on:
  issue_comment:
    types: [created]

jobs:
  process_prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Prompt Extraction
      run: |
        awk '/^### /,/^---$/' prompts/pending-approval.md | head -n 10

    - name: Check for Approval
      if: github.event.comment.body == '✅ Approved'
      run: |
        PROMPT_ENTRY=$(awk '/^### /,/^---$/' prompts/pending-approval.md | head -n 10)
        if [[ -z "$PROMPT_ENTRY" ]]; then
          echo "Error: No prompt found! Check pending-approval.md format."
          exit 1
        fi
        echo "Extracted Prompt: $PROMPT_ENTRY"

        DEPARTMENT=$(echo "$PROMPT_ENTRY" | awk '/\*\*Use Case\*\*: / {print $3; exit}')
        if [[ "$department" == "Architectural Engineering" ]]; then
          TARGET_FILE="prompts/engineering-architectural.md"
        elif [[ "$department" == "Computer Engineering" ]]; then
          TARGET_FILE="prompts/engineering-computer.md"
        elif [[ "$department" == "Chemical and Petrochemical Engineering" ]]; then
          TARGET_FILE="prompts/engineering-chemical.md"
        elif [[ "$department" == "Construction and Building Engineering" ]]; then
          TARGET_FILE="prompts/engineering-construction.md"
        elif [[ "$department" == "Electronics and Communications Engineering" ]]; then
          TARGET_FILE="prompts/engineering-electronics.md"
        elif [[ "$department" == "Electrical and Control Engineering" ]]; then
          TARGET_FILE="prompts/engineering-electrical.md"
        elif [[ "$department" == "Industrial and Management Engineering" ]]; then
          TARGET_FILE="prompts/engineering-industrial.md"
        elif [[ "$department" == "Marine and Offshore Engineering" ]]; then
          TARGET_FILE="prompts/engineering-marine.md"
        elif [[ "$department" == "Mechanical Engineering" ]]; then
          TARGET_FILE="prompts/engineering-mechanical.md"
        elif [[ "$department" == "Oil and Gas Engineering" ]]; then
          TARGET_FILE="prompts/engineering-oil.md"
        else
          TARGET_FILE="prompts/general.md"
        fi

        # ✅ Preserve multi-line formatting when appending
        printf "%s\n" "$PROMPT_ENTRY" >> "$TARGET_FILE"

        # ✅ Use awk instead of sed to remove multi-line prompt safely
        awk 'BEGIN{found=0} /^### /{found=1} found && /^---$/{found=0; next} !found' prompts/pending-approval.md > temp.md && mv temp.md prompts/pending-approval.md

        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add prompts/*
        git commit -m "Approved prompt moved to $TARGET_FILE"
        git push
